### ISSUE TITLE
Is there a demo to generate range-based image?

### ISSUE THREAD

**Issue by FlyerMaxwell** [PRBonn/pole-localization#1]
Hi,
Thanks for sharing your wonderful work. I wonder if there is a demo to reproduce fig-1 (b) and (c) in your paper? Could you provide a demo about that?

**Comment by Chen-Xieyuanli** [comment]
Hey @FlyerMaxwell,

Thanks for your interest in our work! You could find a demo to generate the range image in our previous work OverlapNet here: https://github.com/PRBonn/OverlapNet#demo-1-generate-different-types-of-data-from-the-lidar-scan

**Comment by FlyerMaxwell** [comment]
Thanks for your reply. Cool!
