### ISSUE TITLE
How do you do the inference with this with a pretrained model? 

### ISSUE THREAD

**Issue by jediofgever** [PRBonn/pole-localization#10]

**Comment by donghao51** [comment]
please refer to ncltpoles_learning.py

**Comment by jediofgever** [comment]
Thank you

**Comment by jediofgever** [comment]
What I have is basically only a LIDAR point cloud, which I could convert to a range image with your code. 
I see that a "session" requires a lot more fields, given in nclt dataset, if we imagine I only have .npy file with my point cloud, what would be the most starigh forward way to inference on this?

**Comment by donghao51** [comment]
you can simply convert .npy to range image, normalize it, and use this function https://github.com/PRBonn/pole-localization/blob/09870584b2d35e8ce426f4c5560f81a355c8892b/src/poles_extractor.py#L6

**Comment by jediofgever** [comment]
what did you mean by normalize it?

**Comment by donghao51** [comment]
it is already normalized in the code so you don't need to do this https://github.com/PRBonn/pole-localization/blob/09870584b2d35e8ce426f4c5560f81a355c8892b/src/poles_extractor.py#L22
