### ISSUE TITLE
About save_global_map

### ISSUE THREAD

**Issue by BIT-MJY** [PRBonn/pole-localization#2]
Hi @donghao51,

Thanks for your fantastic work! While reading your code, I found pole-based localization for each session is conducted on the saved global map. However, It seems like the global map is generated from poles extracted from all sessions by the function save_global_map. Whether my understanding is right? If so, why the global map is not generated only by historical sessions instead of all sessions for global localization?

Best wishes!

**Comment by donghao51** [comment]
Hello @BIT-MJY , thanks for your interest in our work! For different sessions, most of the paths are overlapped but not all. For example, some trajectory in 2012-01-15 is not covered by 2012-01-08, if we only use session 2012-01-08 for mapping, for the non-covered part in 2012-01-15 there is no pole correspondence in the global map and the error would be large.

In the mapping part, we use all scans in the first session(2012-01-08 in our case). For the following sessions, we only use scans that have a distance (controlled by _remapdistance_ https://github.com/PRBonn/pole-localization/blob/719d14e2c325a6528e71114691fe15733a6f31eb/src/ncltpoles.py#L90) to the path of the previous session.

**Comment by BIT-MJY** [comment]
Got it. Thx!
