### ISSUE TITLE
About Range Projection & Experiment Settings

### ISSUE THREAD

**Issue by marridG** [PRBonn/pole-localization#4]
Hi. I am recently attempting to use and re-produce some of the functionalities included in the paper, during which, I encounter the following problems:
1. in **range projection**: what if several points (in the raw point cloud) are mapped to the same pixel (in the range image), which is rather likely to happen, however carefully the hyper-parameters are chosen? It seems that only one of these points are preserved ... OR otherwise, how do you handle such cases?
2. in **clustering**: I notice that `numba@jit` is used to accelerate the code execution. However, to the best of my knowledge, `numpy.delete()` is not supported by the `numba` library. What is your comments?
3. about the **experiemnt settings**: in section *IV-C*, the runtime of the proposed method, using CPU only, is "0.09 s for pole extraction" and "less than 0.1 s" for all MCL steps. I am curious about the experiment settings (e.g. CPU type name, RAM size, etc.).

Thanks for you time and looking forward to your reply ^_^ Nice day!

**Comment by donghao51** [comment]
Hello, thanks for your interest in our work!
1. Yes, only the closest point is preserved
2. Please refer to https://github.com/PRBonn/pole-localization/blob/719d14e2c325a6528e71114691fe15733a6f31eb/src/poles_extractor.py#L113
3. The CPU is AMD R5-4600H
