### ISSUE TITLE
use own point cloud dataset

### ISSUE THREAD

**Issue by hhpyy** [PRBonn/pole-localization#7]
If I want to use my own point cloud dataset, do I need to convert them to Kitti data format or change the code?

**Comment by donghao51** [comment]
Hello, you don't have to convert to Kitti data format. But you have to convert your point cloud data into image/range image format, like this line https://github.com/PRBonn/pole-localization/blob/73f30775b75fe1f2e7c6db885d10409aeb1242fd/src/poles_extractor.py#L5

**Comment by hhpyy** [comment]
Thank you very much for your message, so I should write a function myself to replace range_ Projection, it is still possible to directly use this function to convert my point cloud data into image/range image format？

**Comment by donghao51** [comment]
which type of LiDAR do you use? you can replace **fov_up and fov_down** in _range_projection_ with the parameters of your sensor if you know them. Then you can verify the projection by plotting _range_data_ use matplotlib

**Comment by hhpyy** [comment]
Thank you very much for your help, it will be very helpful for my future work!
