### ISSUE TITLE
关于NCLT数据集中点云时间戳和groundtruth.csv时间戳对不齐的问题

### ISSUE THREAD

**Issue by 2653888596** [PRBonn/pole-localization#9]
尊敬的作者
您好！
       最近拜读了您的文章，觉得您当时的idea实在是太厉害了！目前我在follow您工作的时候遇到了一个小问题，如果您能为我解决我将非常感谢！
       1. 在NCLT数据集中，以2012-01-08为例子，在velodyne_sync/中总共有28127帧点云，然而NCLT所给的groundtruth_2012_01-08.csv中有835469条数据，这是由于gps为100hz，而点云只有不到10hz造成的。在我进一步下载NCLT官网的[https://s3.us-east-2.amazonaws.com/nclt.perl.engin.umich.edu/sensor_data/2012-01-08_sen.tar.gz](url)后我发现其中有 odometry_mu.csv, 和点云帧数相对应具有28127项，但我翻阅NCLT官网的论文后发现，此odometry_mu.csv的数据格式代表（官网原始语句）contain 6-DOF odometry measurements synchronized with each image event as described in Section 4. This is calculated relative to the previous image event and follows the same format as above. 我的理解是odometry_mu.csv代表了每帧点云(与图像同步)之间的变化值。但是我将此csv的逐行相加后发现数值并不正确。我看到您的工作也使用了NCLT数据集，同时针对每帧点云生成了对应的Range image，想请问您如何获取每帧点云所在的GPS精确位置呢？以便于未来回环检测的评估工作。
       如果您能抽空解答我的疑惑，我将非常感激！谢谢！

**Comment by donghao51** [comment]
您好，我们是通过插值得到的，具体可以参考这里 
https://github.com/PRBonn/pole-localization/blob/09870584b2d35e8ce426f4c5560f81a355c8892b/src/pynclt.py#L200 的 self.get_T_w_r_gt 函数

**Comment by 2653888596** [comment]
非常感谢您！我最近一直被这个问题所困惑，谢谢！
